<?php

/**
 * 個人プロジェクト
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * PHP version 7.2.5
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class DefaultController extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation petsIdGet
     *
     * ペット詳細を取得する.
     *
     * @param string $id  (required)
     *
     * @return Http response
     */
    public function petsIdGet($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing petsIdGet as a get method ?');
    }
    /**
     * Operation usersIdGet
     *
     * ユーザー詳細を取得する.
     *
     * @param string $id  (required)
     *
     * @return Http response
     */
    public function usersIdGet($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing usersIdGet as a get method ?');
    }
}
